# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv')

### Step 3. Assign it to a variable called

In [3]:
investors=df
investors.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 4.  What is the frequency of the dataset?

In [10]:
investors.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

In [11]:
investors.dtypes

Date                object
Total Equity         int64
Domestic Equity    float64
World Equity         int64
Hybrid             float64
Total Bond           int64
Taxable Bond       float64
Municipal Bond       int64
Total              float64
dtype: object

In [12]:
investors['Date'] = pd.to_datetime(investors['Date'])

In [13]:
investors = investors.set_index('Date')

In [14]:
investors = investors.sort_index()

In [15]:
pd.infer_freq(investors.index)

In [16]:
investors.resample('W').sum()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-10,10167,0.0,3058,0.0,842,0.0,2216,0.0
2022-07-17,7409,0.0,2808,0.0,2067,0.0,741,0.0
2022-07-24,3468,0.0,102,0.0,-417,0.0,519,0.0
2022-07-31,14213,0.0,9667,0.0,8598,0.0,1069,0.0
2022-08-07,9786,0.0,4016,0.0,3079,0.0,937,0.0
...,...,...,...,...,...,...,...,...
2026-03-01,62363,0.0,27334,0.0,8279,0.0,19054,0.0
2026-03-08,24299,0.0,12227,0.0,-652,0.0,12879,0.0
2026-03-15,22797,0.0,11869,0.0,4291,0.0,7578,0.0
2026-03-22,25057,0.0,12807,0.0,2823,0.0,9984,0.0
2026-03-29,40513,0.0,31891,0.0,29748,0.0,2143,0.0

In [17]:
investors.resample('M').mean()

/tmp/ipykernel_40974/1168172770.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  investors.resample('M').mean()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,8814.25,NaN,3908.75,NaN,2772.50,NaN,1136.25,NaN
2022-08-31,9719.20,NaN,6469.60,NaN,6741.00,NaN,-271.40,NaN
2022-09-30,3443.75,NaN,2581.00,NaN,2907.25,NaN,-326.25,NaN
2022-10-31,20719.75,NaN,13911.00,NaN,11858.75,NaN,2052.25,NaN
2022-11-30,16546.20,NaN,10862.80,NaN,7469.60,NaN,3393.40,NaN
2022-12-31,10112.75,NaN,7281.00,NaN,4568.25,NaN,2712.25,NaN
2023-01-31,8722.75,NaN,1962.25,NaN,-2499.00,NaN,4461.25,NaN
2023-02-28,3321.00,NaN,4127.00,NaN,1560.75,NaN,2566.00,NaN
2023-03-31,5772.20,NaN,742.60,NaN,500.00,NaN,242.60,NaN
2023-04-30,9930.75,NaN,4764.50,NaN,3606.50,NaN,1158.00,NaN
2023-05-31,4757.80,NaN,1275.40,NaN,404.00,NaN,871.60,NaN
2023-06-30,15597.50,NaN,12666.25,NaN,9813.50,NaN,2852.00,NaN
2023-07-31,15791.00,NaN,11504.75,NaN,9619.75,NaN,1884.75,NaN
2023-08-31,3746.00,NaN,2393.40,NaN,2176.00,NaN,217.80,NaN
2023-09-30,9468.75,NaN,7490.75,NaN,7457.50,NaN,33.25,NaN
2023-10-31,6893.00,NaN,3486.75,NaN,3593.75,NaN,-107.25,NaN
2023-11-30,22877.20,NaN,15768.60,NaN,14682.20,NaN,1086.60,NaN
2023-12-31,28139.50,NaN,24774.25,NaN,20092.00,NaN,4682.25,NaN
2024-01-31,11788.40,NaN,7360.40,NaN,6156.00,NaN,1204.40,NaN
2024-02-29,11065.25,NaN,9017.25,NaN,6813.00,NaN,2204.50,NaN
2024-03-31,26394.50,NaN,21916.50,NaN,19154.50,NaN,2761.75,NaN
2024-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-31,15868.80,NaN,10387.60,NaN,8470.60,NaN,1916.80,NaN
2024-06-30,19784.50,NaN,12968.00,NaN,9935.25,NaN,3032.75,NaN
2024-07-31,33519.50,NaN,24571.25,NaN,23921.50,NaN,649.50,NaN
2024-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09-30,31251.25,NaN,18221.50,NaN,12150.75,NaN,6070.50,NaN
2025-10-31,39730.00,NaN,26946.00,NaN,21156.00,NaN,5790.00,NaN
2025-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-02-28,45908.25,NaN,27095.75,NaN,12402.00,NaN,14693.50,NaN
2026-03-31,28166.50,NaN,17198.50,NaN,9052.50,NaN,8146.00,NaN

### Step 5. Set the column Date as the index.

In [18]:
investors.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 6. What is the type of the index?

In [19]:
investors.index.dtype

dtype('<M8[ns]')

### Step 7. Set the index to a DatetimeIndex type

In [20]:
investors.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [22]:
monthly = investors.resample('M').sum()

/tmp/ipykernel_40974/2218340783.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly = investors.resample('M').sum()

In [23]:
investors.index = pd.to_datetime(investors.index)
monthly = investors.resample('M').sum()

/tmp/ipykernel_40974/2127914191.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly = investors.resample('M').sum()

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [25]:
monthly = monthly.dropna(how='all')

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [26]:
yearly = investors.resample('Y').sum()
yearly

/tmp/ipykernel_40974/4193703886.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  yearly = investors.resample('Y').sum()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-12-31,303689,0.0,197389,0.0,159480,0.0,37908,0.0
2023-12-31,577223,0.0,384006,0.0,301790,0.0,82214,0.0
2024-12-31,501341,0.0,362632,0.0,312430,0.0,50200,0.0
2025-12-31,204465,0.0,126778,0.0,90915,0.0,35862,0.0
2026-12-31,296299,0.0,177177,0.0,85818,0.0,91358,0.0

### BONUS: Create your own question and answer it.