# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [4]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

In [5]:
df=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')

### Step 3. Assign it to a variable called baby_names.

In [6]:
baby_names=df

### Step 4. See the first 10 entries

In [7]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [8]:
baby_names.drop(['Unnamed: 0','Id'],axis=1,inplace=True)

In [9]:
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [12]:
baby_names.Gender.value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

In [13]:
baby_names.Gender.value_counts().idxmax()

'F'

### Step 7. Group the dataset by name and assign to names

In [14]:
baby_names.groupby('Name').sum()

,Year,Gender,State,Count
Name,,,,
Aaban,4027,MM,NYNY,12
Aadan,8039,MMMM,CACACATX,23
Aadarsh,2009,M,IL,5
Aaden,393963,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,ALALALALALALALARARARAZAZAZAZAZAZCACACACACACACA...,3426
Aadhav,2014,M,CA,6
...,...,...,...,...
Zyra,14085,FFFFFFF,CACACAFLTXTXTX,42
Zyrah,4024,FF,CATX,11
Zyren,2013,M,TX,6
Zyria,20089,FFFFFFFFFF,GAGAGALALALATXTXTXTX,59
Zyriah,18087,FFFFFFFFF,GAGALATXTXTXTXTXTX,58

### Step 8. How many different names exist in the dataset?

In [15]:
baby_names.Name.nunique()

17632

### Step 9. What is the name with most occurrences?

In [16]:
baby_names.Name.value_counts().idxmax()

'Riley'

### Step 10. How many different names have the least occurrences?

In [32]:
baby_names.Name.value_counts()

Name
Riley        1112
Avery        1080
Jordan       1073
Peyton       1064
Hayden       1049
             ...
Anaka           1
Montanna        1
Thaddaeus       1
Miroslav        1
Ackley          1
Name: count, Length: 17632, dtype: int64

In [36]:
baby_names[baby_names.Name=='Riley']['Count']

33         17
255        13
530         8
669        17
871        17
           ..
1015597    11
1015769    12
1015973     8
1016154     7
1016273    12
Name: Count, Length: 1112, dtype: int64

In [50]:
a = baby_names.groupby('Name')["Count"].sum().min()
a

5

In [51]:
count = (baby_names.groupby('Name')["Count"].sum() == a).sum()
count

np.int64(2578)

In [44]:
a.value_counts()

Count
5       2578
6        751
10       700
11       474
12       279
        ...
2746       1
2737       1
2734       1
2729       1
2661       1
Name: count, Length: 3279, dtype: int64

### Step 11. What is the median name occurrence?

In [55]:
baby_names.groupby('Name')["Count"].sum().median()

49.0

### Step 12. What is the standard deviation of names?

In [56]:
baby_names.groupby('Name')["Count"].sum().std()

11006.069467891111

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [57]:
baby_names.groupby('Name')["Count"].sum().describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64